version: "3.7"

services:
  backend:
    env_file:
      - ./backend/.env
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
